### ISSUE TITLE
Wrapper Script start-gretl.sh funktioniert nicht, wenn mehr als ein Parameter übergeben wird

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#81]
Habe festgestellt, dass das Wrapper Script _start-gretl.sh_ nicht richtig funktioniert, wenn man mehr als einen Parameter (`-Pparam1=1 -Pparam2=2`) übergibt.

Verwendeter Befehl:
`./start-gretl.sh --docker_image chrira/jobrunner:19 --job_directory ~/gretljobs/test_wrapper_script/ --task_name printProps -Pparam1=1 -Pparam2=2`

Verwendetes Gradle Script:
```
task printProps {
        doLast {
                println param1
                println param2
        }
}
```

Output:
```
=======================================================
Starts the GRETL runtime to execute the given GRETL job
Docker Image: chrira/jobrunner:19
task name: printProps
job directory: /home/barpasan/development/gretljobs/test_wrapper_script/
task_parameter: -Pparam1=1 -Pparam2=2
=======================================================
Unable to find image 'chrira/jobrunner:19' locally
19: Pulling from chrira/jobrunner
85432449fd0f: Already exists 
400471023d31: Pull complete 
2cd55a7a6e1f: Pull complete 
75ff605727a3: Pull complete 
138dababb744: Pull complete 
29049dff12b7: Pull complete 
a20668cdf76d: Pull complete 
38a4132fa550: Pull complete 
b4d76cbc9dcb: Pull complete 
5de842711c04: Pull complete 
95cece47b04d: Pull complete 
2965f4b7c933: Pull complete 
5b1ae8841326: Pull complete 
919db65b7ac4: Pull complete 
3c601039527f: Pull complete 
87402f9d9fc6: Pull complete 
Digest: sha256:ca034122720d8d6dd144d68eed8e6673315c8df93670ad2621eb7def1662b9fd
Status: Downloaded newer image for chrira/jobrunner:19
jenkins build
date: 2018-01-03 09:43:10
BUILD_NUMBER: 19
BUILD_TAG: jenkins-gretl-runtime-build-19
Starting a Gradle Daemon (subsequent builds will be faster)
:printProps
1
:printProps FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/gradle/project/build.gradle' line: 4

* What went wrong:
Execution failed for task ':printProps'.
> Could not get unknown property 'param2' for task ':printProps' of type org.gradle.api.DefaultTask.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':printProps'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'param2' for task ':printProps' of type org.gradle.api.DefaultTask.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
	at org.gradle.api.DefaultTask_Decorated.getProperty(Unknown Source)
	at build_7ism5ojjxvkfld9af7wo33yib$_run_closure1$_closure2.doCall(/home/gradle/project/build.gradle:4)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:700)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:673)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 28 more


* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed
```

Woran könnte das liegen?

**Comment by schmandr** [comment]
Mit `${task_parameter[*]}` statt `${task_parameter[@]}` (ist das wirklich dasselbe?) scheint es zu funktionieren. Hat also wohl etwas mit der Shell des Docker Images zu tun.

**Comment by chrira** [comment]
Das Problem war beim start-gretl.sh Skript, es hat nur den ersten Parameter weiter an den Docker Container gegeben.

Wurde mit Commit 17b07f1c304cc6b4684b79858e01782534a52c77 behoben.
